### ISSUE TITLE
Core Library not find.

### ISSUE THREAD

**Issue by tornadocean** [OPCFoundation/Misc-Tools#1]
submodule update for local library Core, but not find the repository.

Cloning into 'CertificateGenerator/stack'...
remote: Repository not found.
fatal: repository 'https://github.com/OPCFoundation/UA-AnsiC/' not found
Clone of 'https://github.com/OPCFoundation/UA-AnsiC' into submodule path 'CertificateGenerator/stack' failed

**Comment by tur0kk** [comment]
I have the same problem, when opening the CertificateGenerator project the Ua-Stack folder is completely missing.

**Comment by randy-armstrong** [comment]
Posted fix.
