### ISSUE TITLE
issue during compiling of CertificateGenerator in VS2015

### ISSUE THREAD

**Issue by rudoq32** [OPCFoundation/Misc-Tools#11]
I am having an issue with compiling CertificateGenerator Solution.
I compiled openssl 1_1_0-stable
>>F:\OpenSSL>perl Configure VC-WIN32
>> nmake
while I am trying to compile the project in VS2015 I am having errors like:
1>opcua_p_openssl_x509.c(1012): error C2037: left of 'type' specifies undefined struct/union 'evp_pkey_st'
1>opcua_p_openssl_x509.c(1012): error C2198: 'EVP_PKEY_type': too few arguments for call
1>opcua_p_openssl_x509.c(1157): error C2037: left of 'type' specifies undefined struct/union 'evp_pkey_st'
1>opcua_p_openssl_x509.c(1157): error C2198: 'EVP_PKEY_type': too few arguments for call
1>opcua_p_openssl_x509.c(1253): error C2037: left of 'signature' specifies undefined struct/union 'x509_st'
1>opcua_p_openssl_x509.c(1261): error C2037: left of 'signature' specifies undefined struct/union 'x509_st

do you have any suggestions how can I fix them?
Thanks Rudo

**Comment by opcfoundation-org** [comment]
The tool requires OpenSSL 1.0.2.
Will update the readme.

**Comment by opcfoundation-org** [comment]
Upgraded to 1.1.1.
