### ISSUE TITLE
Cannot build the generator because of openssl

### ISSUE THREAD

**Issue by davy7125** [OPCFoundation/Misc-Tools#14]
Hello,
I'm trying to build the certificate generator. The issue is openssl:
* I installed Win32 OpenSSL v1.1.1 with an installer at this page: http://slproweb.com/products/Win32OpenSSL.html
* in the solution I specified a new directory for the includes
=> the result is a lot of errors such as "undefined type x509_st", "undefined type x509_extension_st", "undefined type asn1_object_st", ...

Which version should we use? Is it possible to document this step? Or directly provide a compiled version?

Regards,
Davy

**Comment by davy7125** [comment]
I shouldn't complain here but compared to other protocols, OpcUA is a complete mess. Everything needs to be compiled, resources cannot be found and days are spent to try gathering everything. Even a simple certificate generator is a pain.

I learned that the license prevents compiled version to be provided outside their website https://opcfoundation.org (which is also a mess). But here is one:
https://www.pconlife.com/download/otherfile/98469/0274bdcdfb8e81084f1a8113aaa0e012/
(there is a link after the captcha)

I hope it will help other guys running out of patience!

**Comment by opcfoundation-org** [comment]
The tool needs OpenSSL 1.0.2.
There is readme and batch file that simplifies the process to a single step.

Not sure what that link is about. Older versions were flagged by virus checkers because did not like console programs started by other processes, That has been fixed in the current version.

**Comment by opcfoundation-org** [comment]
OK, update: the user experience should be much better now:
1) No need to download or build OpenSSL; Clone, Open VS and Build;
2) Upgraded to 1.1.1b;

Please indicate if you have further issues.

**Comment by davy7125** [comment]
Great!
I downloaded the project, opened the file "CertificateGenerator Solution.sln" with Visual Studio (2015), generated Opc.Ua.CertificateGenerator in release mode and everything built smoothly!
Thanks a lot
