### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by shirenfeng** [OPCFoundation/Misc-Tools#15]
I use bellow command to make server's certificate and client's certificate:

Opc.Ua.CertificateGenerator.exe -cmd issue -sp . -an jmApp -au urn:srfJM:jmApp -o JM -dn srf -pw srf123456

Opc.Ua.CertificateGenerator.exe -cmd issue -sp ./server -an jmApp -ikf private/jmApp.pfx -ikp srf123456
Opc.Ua.CertificateGenerator.exe -cmd issue -sp ./client -an jmApp -ikf private/jmApp.pfx -ikp srf123456

Opc.Ua.CertificateGenerator.exe -cmd request -pbf ./certs/jmApp.der -pvf ./private/jmApp.pfx -pvp srf123456 -rfp ./server/server.csr
Opc.Ua.CertificateGenerator.exe -cmd request -pbf ./certs/jmApp.der -pvf ./private/jmApp.pfx -pvp srf123456 -rfp ./client/client.csr

Opc.Ua.CertificateGenerator.exe -cmd process -rfp ./server/server.csr -ikf ./private/jmApp.pfx -ikp srf123456 -pbf ./server/serverCertFile.der
Opc.Ua.CertificateGenerator.exe -cmd process -rfp ./client/client.csr -ikf ./private/jmApp.pfx -ikp srf123456 -pbf ./client/clientCertFile.der

I use clientCertFile.der and  serverCertFile.der,can not open security channel.

**Comment by shirenfeng** [comment]
@hansgschossmann

**Comment by hansgschossmann** [comment]
@shirenfeng, without more information on your use case and what happened at runtime it is not possible to give any feedback on this.

@marcschier, have you folks an idea.

**Comment by shirenfeng** [comment]
The certificates are right , open62541 program configure error .
