### ISSUE TITLE
Could you provide a COMPILED VERSION for this?

### ISSUE THREAD

**Issue by thirteenmans** [OPCFoundation/Misc-Tools#4]
It looks like below projects were missed:
- stack\core\opcua_core.vcxproj
- stack\stackcore\opcua_stackcore.vcxproj
- stack\platforms\win32\UA AnsiC Win32 Platform Layer.vcxproj

Is that UA ANSI C Stack? 
Could you please provide a **COMPILED VERSION** for the UA Certivicate Generator?

**Comment by randy-armstrong** [comment]
OPC Foundation policy requires that all binaries be download from the website.
I added a link to the appropriate download in the README.
Build issues are now fixed.
