### ISSUE TITLE
build_openssl fails

### ISSUE THREAD

**Issue by njkowlski** [OPCFoundation/Misc-Tools#8]
When executing the build_openssl.bat file from the Visual Studio command  prompt I receive the following issue on the "Creating Makefiles...". "'.\ms\do_ms.bat' is not recognized as an internal or external command, operable program or batch file." The "do_ms.bat" does not exist in the "\src\openssl\ms" folder. I pulled the files for openssl from https://github.com/openssl/openssl. Any help would be much appreciated.

Thanks,
Nick

**Comment by foerbsn** [comment]
I also cannot build the openssl files using "build_openssl.bat". Also a direct include in Visual Studio does not work.

The errors are (German, if you need a translation, just tell me):
Der Befehl "Foundation" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
STEP 1) Configure OpenSSL for VC-WIN32...
Der Befehl "perl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
STEP 2) Creating Makefiles...
Der Befehl ".\ms\do_ms.bat" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Microsoft (R) Program Maintenance Utility, Version 14.00.24210.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

NMAKE : fatal error U1052: Datei ".\ms\nt.mak" nicht gefunden
Stop.

Microsoft (R) Program Maintenance Utility, Version 14.00.24210.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

NMAKE : fatal error U1052: Datei ".\ms\nt.mak" nicht gefunden
Stop.
Der Befehl "Foundation" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
STEP 3) Building OpenSSL

Microsoft (R) Program Maintenance Utility, Version 14.00.24210.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

NMAKE : fatal error U1052: Datei ".\ms\nt.mak" nicht gefunden
Stop.
STEP 4) Install OpenSSL...

Microsoft (R) Program Maintenance Utility, Version 14.00.24210.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

NMAKE : fatal error U1052: Datei ".\ms\nt.mak" nicht gefunden
Stop.
*** ALL DONE ***

**Comment by opcfoundation-org** [comment]
You need to install perl.
http://strawberryperl.com/
