### ISSUE TITLE
still SHA1 or not

### ISSUE THREAD

**Issue by eoursel** [OPCFoundation/Misc-Tools#9]
A quick question. I tried with the last binary from OPC Foundation. Looks like CertificateGenerator generates SHA1 certificates which are deprecated and rejected for example by the NETCORE server. 

Is there an  update to CertificateGenerator to generate valid certificates and CA which will be accepted by the last OPC UA servers especially NETCORE branch? 

I didnt try to recompile it myself yet.  

Thanks

**Comment by opcfoundation-org** [comment]
Fixed now.
